services:
  be:
    image: dd-be
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/"
      JDBC_DATABASE_USERNAME: "postgres"
      JDBC_DATABASE_PASSWORD: ""
    ports:
      - "9080:9080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./build/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dddb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
