name: "Check version"
description: "Checks if the project has a unique version"

runs:
    using: composite
    steps:
        -   name: get version
            shell: bash
            run: echo "version=$(${{github.workspace}}/gradlew -q -PisOnMaster=${{ github.ref == 'refs/heads/master' }} printVersion)" >> $GITHUB_ENV

        -   name: Check unique version
            uses: actions/github-script@v7
            with:
                script: |
                    const semver = require('semver');
                    
                    const version = '${{ env.version }}';
                    const ref = '${{ github.ref }}';
                    
                    if (!semver.valid(version)) {
                      throw Error(`Current ${version} version is not semantically valid.`);
                    }
                    
                    const ghReleases = await github.paginate(github.rest.repos.listReleases, {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        per_page: 100,
                    });
                    
                    const latestVersion = ghReleases
                        .filter(o => o.prerelease === false)
                        .map(o => o.tag_name)
                        .sort(semver.rcompare)[0];
                    
                    if (!semver.lt(latestVersion, version)) {
                      throw Error(`The current version ${version} should be higher than the latest released ${latestVersion} version.`)
                    }
