name: CI

on: [ pull_request ]

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

env:
    DD_GH_USERNAME: ${{ secrets.DD_GH_USERNAME }}
    DD_GG_TOKEN: ${{ secrets.DD_GG_TOKEN }}

jobs:
    verify:
        runs-on: self-hosted
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   uses: gradle/gradle-build-action@v2
            -   uses: android-actions/setup-android@v3

            -   name: Lint
                run: ./gradlew lintKotlin --build-cache --stacktrace

            -   name: Common unit tests
                run: ./gradlew allTests --build-cache

            -   name: Android check
                run: ./gradlew :androidApp:check
