name: CI

on: [ pull_request ]

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    verify:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   uses: gradle/gradle-build-action@v2
            -   uses: android-actions/setup-android@v3

            -   name: Lint
                run: ./gradlew lintKotlin --build-cache --stacktrace

            -   name: Check
                run: ./gradlew allTests --build-cache
