name: CI

on:
    push:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    DD_GH_USERNAME: ${{ secrets.DD_GH_USERNAME }}
    DD_GG_TOKEN: ${{ secrets.DD_GG_TOKEN }}

jobs:
    common:
        runs-on: self-hosted
        timeout-minutes: 15
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}
                    token: ${{ secrets.DD_GG_TOKEN }}
                    fetch-depth: 2

            -   uses: ./.github/actions/setup-android

            -   uses: ./.github/actions/check-version
                if: ${{ github.ref != 'refs/heads/master' }}

            -   name: tests
                run: ./gradlew -PisOnMaster=${{ github.ref == 'refs/heads/master' }} :common:check --build-cache

            -   name: publish
                if: ${{ !contains(github.event.head_commit.message, '[published]') }}
                run: ./gradlew -PisOnMaster=${{ github.ref == 'refs/heads/master' }} :common:publish

            -   name: get last commit message
                id: last-commit-message
                if: ${{ !contains(github.event.head_commit.message, '[published]') }}
                run: |
                    echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

            -   name: update swift package
                uses: stefanzweifel/git-auto-commit-action@v5
                if: ${{ !contains(github.event.head_commit.message, '[published]') }}
                with:
                    commit_message: "${{ steps.last-commit-message.outputs.msg }}\n[published]"
                    commit_options: '--amend'
                    push_options: '--force'
                    skip_fetch: true

            -   uses: ./.github/actions/create-tag
                if: ${{ contains(github.event.head_commit.message, '[published]') }}

    android:
        runs-on: self-hosted
        timeout-minutes: 5
        needs: [ common ]
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-android

            -   name: check
                run: ./gradlew -PisOnMaster=${{ github.ref == 'refs/heads/master' }} :androidApp:check

    backend:
        runs-on: self-hosted
        timeout-minutes: 5
        needs: [ common ]
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-gradle

            -   name: check
                run: ./gradlew -PisOnMaster=${{ github.ref == 'refs/heads/master' }} :backEnd:check

    apple:
        runs-on: self-hosted
        timeout-minutes: 5
        needs: [ common ]
        steps:
            -   uses: actions/checkout@v4

            -   name: clear cache
                run: swift package clean && swift package purge-cache && swift package reset && swift package resolve

            -   name: iOS tests
                working-directory: ./iosApp
                run: |
                    xcodebuild test \
                        -project dailydish-ios.xcodeproj \
                        -scheme dailydish-ios \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1' \
                        -configuration Debug

            -   name: macOS tests
                working-directory: ./iosApp
                run: |
                    xcodebuild test \
                        -project dailydish-ios.xcodeproj \
                        -scheme dailydish-ios \
                        -sdk macosx \
                        -configuration Debug

    release:
        runs-on: self-hosted
        timeout-minutes: 5
        needs: [ android, backend, apple ]
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-gradle

            -   uses: ./.github/actions/create-tag
                id: create-tag

            -   name: create release
                uses: ncipollo/release-action@v1
                with:
                    allowUpdates: true
                    generateReleaseNotes: true
                    makeLatest: ${{ github.ref == 'refs/heads/master' }}
                    tag: ${{ steps.create-tag.outputs.version }}
                    draft: ${{ github.ref != 'refs/heads/master' }}
